FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY server ./server
COPY types.ts ./types.ts
COPY tsconfig.json ./tsconfig.json

EXPOSE 3001

CMD ["npm", "run", "dev:server"]